version: "3.7"

services:
  loading-test:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ["--cpu", "1", "--vm", "1", "--vm-bytes", "128M"]
    ports: 
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 256M
